name: "Construção do Artefato"


on: 
    push:
        branches: ["main", "check-dk"]
        workflow_dispatch:

jobs:
    build:
          runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Build da imagem docker 
                run: docker build --target=production -t levizpiromancer/projeto_go_prod:${{github.sha}} .
                